
CREATE DATABASE IOE_SNW;

CREATE SCHEMA IOE_SNW.LANDING;
CREATE SCHEMA IOE_SNW.STAGE;
CREATE SCHEMA IOE_SNW.TEMP;
CREATE SCHEMA IOE_SNW.TARGET;


CREATE STAGE IOE_SNW.LANDING.CSV_FILE
  FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  );


CREATE OR REPLACE TABLE IOE_SNW.LANDING.SALES (
     ROW_ID          VARCHAR
    ,ORDER_ID        VARCHAR
    ,ORDER_DATE      VARCHAR
    ,SHIP_DATE       VARCHAR
    ,SHIP_MODE       VARCHAR
    ,CUSTOMER_ID     VARCHAR
    ,CUSTOMER_NAME   VARCHAR
    ,SEGMENT         VARCHAR
    ,COUNTRY         VARCHAR
    ,CITY            VARCHAR
    ,STATE           VARCHAR
    ,POSTAL_CODE     VARCHAR
    ,REGION          VARCHAR
    ,PRODUCT_ID      VARCHAR
    ,CATEGORY        VARCHAR
    ,SUB_CATEGORY    VARCHAR
    ,PRODUCT_NAME    VARCHAR
    ,SALES           VARCHAR
    ,QUANTITY        VARCHAR
    ,DISCOUNT        VARCHAR
    ,PROFIT          VARCHAR
);


CREATE OR REPLACE VIEW STAGE.STG_D_COUNTRY (
    COUNTRY_NAME
) AS
SELECT DISTINCT TRIM(COUNTRY)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_REGION (
     REGION_NAME
    ,COUNTRY_NAME
) AS
SELECT DISTINCT
     TRIM(REGION)
    ,TRIM(COUNTRY)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_STATE (
     STATE_NAME
    ,REGION_NAME
) AS
SELECT DISTINCT
     TRIM(STATE)
    ,TRIM(REGION)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_CITY (
     CITY_NAME
    ,POSTAL_CODE
    ,STATE_NAME
) AS
SELECT DISTINCT
     TRIM(CITY)
    ,TRIM(POSTAL_CODE)
    ,TRIM(STATE)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_CATEGORY (
    CATEGORY_NAME
) AS
SELECT DISTINCT TRIM(CATEGORY)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_SUBCATEGORY (
     SUBCATEGORY_NAME
    ,CATEGORY_NAME
) AS
SELECT DISTINCT
     TRIM(SUB_CATEGORY)
    ,TRIM(CATEGORY)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_PRODUCT (
     PRODUCT_ID
    ,PRODUCT_NAME
    ,SUBCATEGORY_NAME
) AS
SELECT DISTINCT
     TRIM(PRODUCT_ID)
    ,TRIM(PRODUCT_NAME)
    ,TRIM(SUB_CATEGORY)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_SEGMENT (
    SEGMENT_NAME
) AS
SELECT DISTINCT TRIM(SEGMENT)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_CUSTOMER (
     CUSTOMER_ID
    ,CUSTOMER_NAME
    ,SEGMENT_NAME
) AS
SELECT DISTINCT
     TRIM(CUSTOMER_ID)
    ,TRIM(CUSTOMER_NAME)
    ,TRIM(SEGMENT)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_D_SHIP_MODE (
    SHIP_MODE
) AS
SELECT DISTINCT TRIM(SHIP_MODE)
FROM LANDING.SALES;

CREATE OR REPLACE VIEW STAGE.STG_F_SALES (
     ROW_ID
    ,ORDER_ID
    ,ORDER_DATE
    ,SHIP_DATE
    ,CUSTOMER_ID
    ,PRODUCT_ID
    ,COUNTRY
    ,REGION
    ,STATE
    ,CITY
    ,POSTAL_CODE
    ,SHIP_MODE
    ,QUANTITY
    ,SALES
    ,DISCOUNT
    ,DISCOUNT_AMOUNT
    ,REVENUE
    ,PROFIT
) AS
SELECT
     TRIM(ROW_ID)
    ,TRIM(ORDER_ID)
    ,TO_DATE(ORDER_DATE, 'MM/DD/YYYY')
    ,TO_DATE(SHIP_DATE, 'MM/DD/YYYY')
    ,TRIM(CUSTOMER_ID)
    ,TRIM(PRODUCT_ID)
    ,TRIM(COUNTRY)
    ,TRIM(REGION)
    ,TRIM(STATE)
    ,TRIM(CITY)
    ,TRIM(POSTAL_CODE)
    ,TRIM(SHIP_MODE)
    ,TRIM(QUANTITY)::NUMBER
    ,TRIM(SALES)::FLOAT
    ,TRIM(DISCOUNT)::FLOAT
    ,(TRIM(SALES)::FLOAT * TRIM(DISCOUNT)::FLOAT)
    ,TRIM(SALES)::FLOAT
    ,TRIM(PROFIT)::FLOAT
FROM LANDING.SALES;


CREATE OR REPLACE TABLE TEMP.TMP_D_COUNTRY (
    COUNTRY_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_REGION (
     REGION_NAME  VARCHAR
    ,COUNTRY_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_STATE (
     STATE_NAME  VARCHAR
    ,REGION_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_CITY (
     CITY_NAME    VARCHAR
    ,POSTAL_CODE  VARCHAR
    ,STATE_NAME   VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_CATEGORY (
    CATEGORY_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_SUBCATEGORY (
     SUBCATEGORY_NAME VARCHAR
    ,CATEGORY_NAME    VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_PRODUCT (
     PRODUCT_ID       VARCHAR
    ,PRODUCT_NAME     VARCHAR
    ,SUBCATEGORY_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_SEGMENT (
    SEGMENT_NAME VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_CUSTOMER (
     CUSTOMER_ID   VARCHAR
    ,CUSTOMER_NAME VARCHAR
    ,SEGMENT_NAME  VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_D_SHIP_MODE (
    SHIP_MODE VARCHAR
);

CREATE OR REPLACE TABLE TEMP.TMP_F_SALES (
     ROW_ID          VARCHAR
    ,ORDER_ID        VARCHAR
    ,ORDER_DATE_KEY  NUMBER
    ,SHIP_DATE_KEY   NUMBER
    ,CUSTOMER_KEY    NUMBER
    ,PRODUCT_KEY     NUMBER
    ,CITY_KEY        NUMBER
    ,SHIP_MODE_KEY   NUMBER
    ,QUANTITY        NUMBER
    ,SALES           FLOAT
    ,DISCOUNT        FLOAT
    ,DISCOUNT_AMOUNT FLOAT
    ,REVENUE         FLOAT
    ,PROFIT          FLOAT
);


CREATE OR REPLACE TABLE TARGET.TGT_D_COUNTRY (
     COUNTRY_KEY    NUMBER AUTOINCREMENT PRIMARY KEY
    ,COUNTRY_NAME   VARCHAR
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_REGION (
     REGION_KEY     NUMBER AUTOINCREMENT PRIMARY KEY
    ,REGION_NAME    VARCHAR
    ,COUNTRY_KEY    NUMBER REFERENCES TARGET.TGT_D_COUNTRY(COUNTRY_KEY)
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_STATE (
     STATE_KEY      NUMBER AUTOINCREMENT PRIMARY KEY
    ,STATE_NAME     VARCHAR
    ,REGION_KEY     NUMBER REFERENCES TARGET.TGT_D_REGION(REGION_KEY)
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_CITY (
     CITY_KEY       NUMBER AUTOINCREMENT PRIMARY KEY
    ,CITY_NAME      VARCHAR
    ,POSTAL_CODE    VARCHAR
    ,STATE_KEY      NUMBER REFERENCES TARGET.TGT_D_STATE(STATE_KEY)
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_CATEGORY (
     CATEGORY_KEY   NUMBER AUTOINCREMENT PRIMARY KEY
    ,CATEGORY_NAME  VARCHAR
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_SUBCATEGORY (
     SUBCATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY
    ,SUBCATEGORY_NAME VARCHAR
    ,CATEGORY_KEY     NUMBER REFERENCES TARGET.TGT_D_CATEGORY(CATEGORY_KEY)
    ,EFF_START_DATE   DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE     DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT       BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_PRODUCT (
     PRODUCT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY
    ,PRODUCT_ID       VARCHAR
    ,PRODUCT_NAME     VARCHAR
    ,SUBCATEGORY_KEY  NUMBER REFERENCES TARGET.TGT_D_SUBCATEGORY(SUBCATEGORY_KEY)
    ,EFF_START_DATE   DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE     DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT       BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_SEGMENT (
     SEGMENT_KEY    NUMBER AUTOINCREMENT PRIMARY KEY
    ,SEGMENT_NAME   VARCHAR
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_CUSTOMER (
     CUSTOMER_KEY   NUMBER AUTOINCREMENT PRIMARY KEY
    ,CUSTOMER_ID    VARCHAR
    ,CUSTOMER_NAME  VARCHAR
    ,SEGMENT_KEY    NUMBER REFERENCES TARGET.TGT_D_SEGMENT(SEGMENT_KEY)
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_SHIP_MODE (
     SHIP_MODE_KEY  NUMBER AUTOINCREMENT PRIMARY KEY
    ,SHIP_MODE      VARCHAR
    ,EFF_START_DATE DATE DEFAULT CURRENT_DATE
    ,EFF_END_DATE   DATE DEFAULT '9999-12-31'::DATE
    ,IS_CURRENT     BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE TARGET.TGT_D_DATE (
     DATE_KEY     NUMBER PRIMARY KEY
    ,FULL_DATE    DATE
    ,YEAR         NUMBER
    ,QUARTER      NUMBER
    ,MONTH        NUMBER
    ,MONTH_NAME   VARCHAR
    ,WEEK         NUMBER
    ,DAY          NUMBER
    ,DAY_OF_WEEK  NUMBER
    ,DAY_NAME     VARCHAR
    ,IS_WEEKEND   BOOLEAN
);



CREATE OR REPLACE TABLE TARGET.TGT_F_SALES (
     ROW_ID          VARCHAR PRIMARY KEY
    ,ORDER_ID        VARCHAR
    ,ORDER_DATE_KEY  NUMBER REFERENCES TARGET.TGT_D_DATE(DATE_KEY)
    ,SHIP_DATE_KEY   NUMBER REFERENCES TARGET.TGT_D_DATE(DATE_KEY)
    ,CUSTOMER_KEY    NUMBER REFERENCES TARGET.TGT_D_CUSTOMER(CUSTOMER_KEY)
    ,PRODUCT_KEY     NUMBER REFERENCES TARGET.TGT_D_PRODUCT(PRODUCT_KEY)
    ,CITY_KEY        NUMBER REFERENCES TARGET.TGT_D_CITY(CITY_KEY)
    ,SHIP_MODE_KEY   NUMBER REFERENCES TARGET.TGT_D_SHIP_MODE(SHIP_MODE_KEY)
    ,QUANTITY        NUMBER
    ,SALES           FLOAT
    ,DISCOUNT        FLOAT
    ,DISCOUNT_AMOUNT FLOAT
    ,REVENUE         FLOAT
    ,PROFIT          FLOAT
);



SET start_date = '2022-01-01';
SET row_count = (SELECT DATEDIFF(DAY, '2022-01-01', '2026-12-31') + 1);

INSERT INTO TARGET.TGT_D_DATE
SELECT
    TO_NUMBER(TO_CHAR(d, 'YYYYMMDD'))           AS date_key,
    d                                            AS full_date,
    YEAR(d)                                      AS year,
    QUARTER(d)                                   AS quarter,
    MONTH(d)                                     AS month,
    TO_CHAR(d, 'Mon')                            AS month_name,
    WEEK(d)                                      AS week,
    DAY(d)                                       AS day,
    DAYOFWEEK(d)                                 AS day_of_week,
    TO_CHAR(d, 'Dy')                             AS day_name,
    IFF(DAYOFWEEK(d) IN (0, 6), TRUE, FALSE)     AS is_weekend
FROM (
    SELECT DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY NULL) - 1, $start_date::DATE) AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 2000))
)
WHERE d <= '2026-12-31'::DATE;
